//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behaviour and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.CompilerServices;

namespace QGen.Sample;

[CompilerGenerated]
public static partial class InputHelper {

    public static void ConstructInputs() {
        //InputMove = new Input<Vector2>(KnownInput.Move, "Player/Move", default);
    }

    public static void UpdateAll() {
        //UpdateInput(InputMove);
    }

    //public static Input<Vector2> InputMove { get; private set; } = null!;
}